# Generated by Django 5.0.2 on 2024-03-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_status_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Class',
            new_name='Class_id',
        ),
    ]
