# Generated by Django 5.0.2 on 2024-03-03 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='classes.class'),
        ),
    ]
