# Generated by Django 5.0.2 on 2024-03-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0003_homework_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='date',
        ),
    ]
