# Generated by Django 5.0.2 on 2024-03-09 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0004_remove_homework_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='week',
            field=models.DateField(default=datetime.date(2024, 3, 4)),
        ),
    ]
