# Generated by Django 5.0.2 on 2024-03-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_class_school'),
        ('homeworks', '0005_homework_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='lesson_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='classes.shedule'),
        ),
    ]
