# Generated by Django 5.0.2 on 2024-03-12 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0006_alter_homework_lesson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='week',
            field=models.DateField(default=datetime.date(2024, 3, 11)),
        ),
    ]
