# Generated by Django 5.0.2 on 2024-03-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeworks', '0007_alter_homework_week'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='class_id',
            new_name='class_user',
        ),
        migrations.RenameField(
            model_name='homework',
            old_name='lesson_id',
            new_name='lesson',
        ),
    ]
