# Generated by Django 5.0.2 on 2024-03-08 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_school'),
        ('listUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valid_user',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.school'),
            preserve_default=False,
        ),
    ]
