# Generated by Django 5.0.2 on 2024-03-08 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_class_school'),
        ('listUsers', '0002_valid_user_school'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Valid_user',
            new_name='ValidUser',
        ),
    ]
