# Generated by Django 5.0.2 on 2024-03-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0010_rename_class_id_shedule_class_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
