# Generated by Django 5.0.2 on 2024-03-17 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_alter_class_name_alter_day_name_alter_lesson_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='class_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.class', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.day', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.lesson', verbose_name='Урок'),
        ),
    ]
