# Generated by Django 4.0.6 on 2024-03-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0013_class_count_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='count_student',
            new_name='count_students',
        ),
    ]
