# Generated by Django 4.0.6 on 2024-03-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0015_alter_class_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='shedule',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
