# Generated by Django 4.0.6 on 2024-03-24 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0016_shedule_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='class_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.class', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.day', verbose_name='День недели'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
