# Generated by Django 4.0.6 on 2024-03-24 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0019_alter_shedule_lesson_alter_shedule_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='shedule',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
