# Generated by Django 4.0.6 on 2024-03-24 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0021_alter_shedule_lesson_alter_shedule_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shedule',
            name='lesson',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='classes.lesson', verbose_name='Урок'),
        ),
    ]
